print "git init"
print "Creates a git repository in the current directory"
print "git status"
print "shows the current state of the project and what has been modified"
print "git log"
print "shows a list of all the commit logs recorded"
print "git add <filename>"
print "this is the command you run on a file when you want to include the new changes"
print "git diff A..B"
print "the command that shows you the differences between the commits of A and B"
print "git commit -m"
print "the command where you record your bookmark and add a message to describe what changes you made"
print "test"
