print "git init"
print "Creates a git repository in the current directory"
print "git status"
print "shows the current state of the project and what has been modified"
print "git log"
print "shows a list of all the commit logs recorded"
